-- Mi Mesa — orders table for the "Sipariş Ver" feature (V1).
--
-- Single table. `items` is jsonb (small, denormalised); raporlama/V2'de
-- order_items'a parçalanabilir.
-- RLS açık ama hiçbir public/anon policy YOK — yazma yalnız service_role
-- üzerinden /api/order ile yapılır. Spam/direkt yazma engellenir.

create table if not exists public.orders (
  id              uuid primary key default gen_random_uuid(),
  order_no        bigint generated by default as identity,
  status          text not null default 'new'
                  check (status in ('new','confirmed','preparing','out_for_delivery','delivered','cancelled')),
  lang            text not null default 'tr'
                  check (lang in ('tr','en','ar')),

  customer_name   text not null,
  customer_phone  text not null,
  customer_email  text,
  address         text not null,
  address_note    text,
  note            text,

  payment_method  text not null default 'cash'
                  check (payment_method in ('cash','card')),

  items           jsonb not null,           -- [{slug,name,qty,unit_price,line_total,price_label}]
  total_amount    numeric(10,2) not null,
  currency        text not null default 'TRY',

  ip              text,
  user_agent      text,
  source          text not null default 'web',
  telegram_message_id text,                 -- V2 hookup (inline kabul/red butonları)

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);

create unique index if not exists orders_order_no_idx on public.orders(order_no);
create index if not exists orders_status_idx          on public.orders(status);
create index if not exists orders_created_idx         on public.orders(created_at desc);

drop trigger if exists orders_touch on public.orders;
create trigger orders_touch
  before update on public.orders
  for each row execute function public.touch_updated_at();

alter table public.orders enable row level security;
-- Intentionally NO anon/authenticated policies. Only service_role inserts.
